### ISSUE TITLE
quotes around strings are not trimmed

### ISSUE THREAD

**Issue by tvogt** [mtschoen/JSONObject#15]
I'm using JSON with quoted strings, e.g.

"key": "value"

And all my values are, when I use ToString() not value, but "value" - with quotes retained. So I have to add .Trim('"') to all the requests and started to wonder if that isn't a bug.

**Comment by mtschoen** [comment]
Yeah it's a bit of an odd behavior.  The reason why ToString() on the object itself returns the string with quotes is that it's used internally for the "stringify" process.  If you want the string without quotes, try just accessing theObject.str.

I suppose that for an object which contains just a string I could add a special print function which is not part of stringify... but lazy :)

**Comment by tvogt** [comment]
Thanks for that pointer. The various accessors like .str or .i are not very clear in the documentation (and that .i returns a long and not an int is a bug, yes?). It could be made much more clear. I'm now using .str and that solves my issues.

**Comment by mtschoen** [comment]
Ah, yeah I guess I could make a point of it in the docs.  And .i returns a long since it is the most inclusive data type.  Technically "i" is referring to "integer" in the mathematical sense, not "int," but really the reason for that letter choice is that it originally _was_ an int, and then I realized I need to support longs.

I'll go modify the docs at some point soon to make it clear that you should use .str
