### ISSUE TITLE
Loading bar when parse large Json ? 

### ISSUE THREAD

**Issue by tienhagioi** [mtschoen/JSONObject#22]
I need parse large JSON ( ~ 2mb ) in unity . But when use this code :
`JSONObject dataObj = new JSONObject (_data);` 
game paused like Time.timeScale = 0  about 25s (Only sound play).
I need make a loadingbar while it parsing data .How to do that ?

**Comment by mtschoen-unity** [comment]
Hi there. There is currently no way to parse data asynchronously, but it wouldn't be hard. Basically all you need to do is duplicate the Parse method as an IEnumerator and call it as a coroutine. I don't have the time to do this right now, but I'll give it a shot soon. The tricky part is when to yield, because you don't know if your data is very deep or very broad, but either way, just yielding after every few hundred properties should be fine.

**Comment by wouterswim** [comment]
Hi Matt,

First of all thanks for you time-saving script!
I'm having some problems with parcing lag too... get a 3 sec freeze when loading 2mb of JSON data.

> Basically all you need to do is duplicate the Parse method as an IEnumerator and call it as a coroutine.

Tried this, and wasn't so simple :)
"try catch return" does not work with IEnumerators

I'll do some more tweeks, see if I get it working... but if you have anything ready already... please share!
:P

**Comment by mtschoen** [comment]
Try this: https://msdn.microsoft.com/en-us/library/system.int32.tryparse(v=vs.110).aspx

I wasn't aware of it at time when I first wrote the parser.

**Comment by brean** [comment]
Has anyone tried the new .Net 4.6 await/async for this yet (Its marked as Experimental for Unity 2017)?

**Comment by mtschoen** [comment]
I ended up hitting this in the 2.1 release. There's now a `JSONObject.CreateAsync` method that can be used to parse asynchronously. This actually inspired me to rewrite the parser to be faster and not rely on substrings! It now works without going backwards or re-parsing any of the input string, and you can specify a start/end for where you want to parse. Fancy!

For an example of how to show progress, check out this test: https://github.com/mtschoen/JSONObject/blob/master/Editor/JSONObjectAsyncTests.cs#L50
