### ISSUE TITLE
Thank you for great library

### ISSUE THREAD

**Issue by rico345100** [mtschoen/JSONObject#25]
This is one of "JavaScript" like library that I'm looking for. JavaScript and C# are my favorite languages but using JSON in C# is pretty shitty.

This library do not require something like "pre-defined" json scheme, I can use it dynamically just like JavaScript I always do, and that is the nature of JSON I think. Simple, extendable, easy!

Thank you for create this awesome library. Thanks!
When you read this, you can close this.

**Comment by mtschoen-unity** [comment]
Thanks yourself! Although, class-based or schema-based serialization has its merits. Before dismissing it as "pretty shitty," keep an open mind to how it might help you in the future. Also, since I wrote this ages and ages ago, Unity has provided built-in JSON serialization, in case this helps:

https://docs.unity3d.com/Manual/JSONSerialization.html

Also something I'm really hoping to support with this is interop with BSON to avoid the cost of string manipulation. The BAKED feature kind of helps, but ultimately working with big strings is just a bad idea.

**Comment by mtschoen** [comment]
Thanks yourself! Although, class-based or schema-based serialization has its merits. Before dismissing it as "pretty shitty," keep an open mind to how it might help you in the future. Also, since I wrote this ages and ages ago, Unity has provided built-in JSON serialization, in case this helps:

https://docs.unity3d.com/Manual/JSONSerialization.html

Also something I'm really hoping to support with this is interop with BSON to avoid the cost of string manipulation. The BAKED feature kind of helps, but ultimately working with big strings is just a bad idea.
