### ISSUE TITLE
I think you are missing a case for Deep string value,  please loot at this example

### ISSUE THREAD

**Issue by SteveStrong** [mtschoen/JSONObject#35]
{
   "Version": 21,
   "BaseTime": "2017-1-1T0.000000:0.000000:0.000000z type: 1",
   "BaseTimeSec": 0.000000,
   "range": {
      "Name": "xxxxDelta1123",
      "minTime": -20940600.000000,
      "maxTime": -20917800.000000,
   }
}

xxxxDelta1123  will fail to parse  because your code only allows values to be numbers when inside a  {}

**Comment by mtschoen** [comment]
Hm... I don't seem to get the same result. If I paste that string into the JSONChecker window, I see the same output. Those numbers do not show their decimal part, but that's because whole numbers don't stringify that way.

Can you explain more about the problem you are seeing? Are you using the BAKE feature?

**Comment by mtschoen** [comment]
I tested this input on the latest version and it seems to work. Feel free to re-open if this is still an issue.
