### ISSUE TITLE
Use double precision as default (or better: support double in addition)

### ISSUE THREAD

**Issue by derwaldgeist** [mtschoen/JSONObject#38]
Thanks for this library. One thing that surprises me is that it uses float by default and only offers doubles if you comment out the USEFLOAT directive (and if you do, you get a compiler error). We're using it to transfer geospatial data, and if I cast the latitudes and longitudes to floats, there is a significant rounding error.

Why is float the default anyways? IMHO, doubles would work better, since JavaScript numbers are doubles anyways and thus this seems to be a better match to JSON.

If there is a specific reason as to why to use floats, I would strongly recommend to at least support doubles by additional constructors / Add() methods.

Since I did not want to patch the library itself, I am now converting the doubles to strings, transfer them as such, and re-parse them to JavaScript numbers on the server-side. Which is a pretty weird workaround.

**Comment by mtschoen-unity** [comment]
Uh oh.. what's the compile error if you comment out USEFLOAT? I haven't used doubles in a while. It is likely a quick fix. The issue is that when we output some floating point numbers, the stringified version has extraneous significant digits and can end up being interpreted differently when parsed, sometimes even resulting in a different float value than you had originally.

Most of the values you end up dealing with in Unity are floats, and I didn't have a need originally to use both within a single application. The issue with supporting both is that, during parsing, I would either have to parse both a double *and* a float, or introduce some extra flag to indicate that, which would make it invalid JSON. I can foresee doing it this way as a third option. If I have the time I will look into this.

**Comment by mtschoen** [comment]
Uh oh.. what's the compile error if you comment out USEFLOAT? I haven't used doubles in a while. It is likely a quick fix. The issue is that when we output some floating point numbers, the stringified version has extraneous significant digits and can end up being interpreted differently when parsed, sometimes even resulting in a different float value than you had originally.

Most of the values you end up dealing with in Unity are floats, and I didn't have a need originally to use both within a single application. The issue with supporting both is that, during parsing, I would either have to parse both a double *and* a float, or introduce some extra flag to indicate that, which would make it invalid JSON. I can foresee doing it this way as a third option. If I have the time I will look into this.

**Comment by derwaldgeist** [comment]
Thanks for the response. The compile error is already described here: https://github.com/mtschoen/JSONObject/issues/14

The problem with floats is that they round digits to their closest float representation.  In the case of GPS location data, this leads to a high (intolerable) amount of offset. I workarounded this for now by converting my doubles to strings and re-parsing these strings into doubles on server-side. But this is not really a nice solution.

**Comment by mtschoen** [comment]
I finally pulled down the latest version and checked this out. Lucky for you, I made the decision to blow away the Animation-related templates, and all of the templates beyond the basic Vector types, since they are dependent on Unity versions, and create warnings due to referencing deprecated fields. It's possible to support all the Unity versions with preprocessor defines, but I'm not sure anyone was getting much use out of those templates anyway.

So you should be able to pull down the latest, comment out USEFLOAT, and parse doubles. You may find the need to add a USELONG switch for the same reason, but I think doubles mode should do the trick for GPS.

There is also the `.f` property to access the number value of a JSONObject as a float--all it does is cast the double value to a float. I haven't tested every possible value, but I think there might be some situations where floats that are cast to double, stringified, and then parsed to double and cast back down to float will actually modify the value.

**Comment by derwaldgeist** [comment]
I totally missed your update until I ran into the same problem today. Thanks a lot for providing this! However, there's still one problem: There is no `Add` method that accepts a double instead of a float. So, parsing `doubles` works now, but I can't add doubles to a JSON object.

**Comment by mtschoen** [comment]
The latest version uses doubles by default and I have added some test coverage for various float/double values. You can define `JSONOBJECT_USE_FLOAT` if you want to use floats like the old version does.
