### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nickjanssen** [mtschoen/JSONObject#4]
Thank you for putting this out there, it's been very useful to me!
Could you please clarify what's the license of this? Any chance you could make it MIT?

**Comment by mtschoen** [comment]
The main script links to LGPL 2.1, which is the license I chose for this long ago

https://github.com/mtschoen/JSONObject/blob/master/JSONObject.cs#L13-L18

That said, I (the sole author) am not really a stickler on licenses and I'm not opposed to anyone using, redistributing, or profiting from anything that uses the script, as long as the license and credit appears as-is.  If you try to take ownership and/or sell the tool you'll probably get an angry letter from me insisting that you stop, but otherwise do what you want! :)
