### ISSUE TITLE
Double Encoded Json Issues

### ISSUE THREAD

**Issue by jefferson-kaneta-oktagon** [mtschoen/JSONObject#7]
I have a Json Object that contains a Json object, after the encoding I end up with a string containing a double encoded JSON, after trying to parse it with your lib I notice that the inner JSON isn't parsed and you Lib does not support the parsing of double encoded JSONs, could you add  the feature to escape JSON strings in your lib?

**Comment by mtschoen** [comment]
Hm. I actually have used "embedded" JSON strings without issue in the past.  Are you escaping the quotes in your embedded string?  Could you send me your JSON data, or an equivalent piece of data that breaks the parser?

**Comment by jefferson-kaneta-oktagon** [comment]
Hello, 

it was something like
\"{
\"myjson\" : {
    \"inner_json\": "{\\\"double_encoded\\\" : \\\"string\\\"}"
 }
 }\"

I generated the json in PHP using 
$myjson = json_encode($inner_json)
return json_encode($myjson);

I had some troble getting the inner_json, I had to escape the slashes to use JSON.

**Comment by mtschoen** [comment]
Thanks. I'll look into this when I have a chance

**Comment by mtschoen** [comment]
Hm. I'm having trouble testing this exactly.  I didn't look carefully at the data at first.  Could you show me the actual PHP code or output?  The data you posted is simply not valid JSON.  If you're using that as a string valriable in code, then I think you would get an error, since the quotes around the json-object within inner_json would close your quote.

If you put that particular data into any JSON parser it will not parse.

**Comment by mtschoen** [comment]
It seems that you have the same issue as another user who sent a pull request.  I realize the underlying issue is that you can't use a \" in front of a field name.  I'm going to close this as a non-issue.

The parser should not correctly parse invalid JSON.
